// Generated by nitro
import type { Serialize, Simplify } from 'nitropack'
declare module 'nitropack' {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/cached': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/cached.get').default>>>>
    }
    '/api/images/:pathname': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/images/[pathname].delete').default>>>>
    }
    '/api/images': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/images/index.get').default>>>>
    }
    '/api/images/upload': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/images/upload.post').default>>>>
    }
    '/api/messages': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/messages/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/messages/index.post').default>>>>
    }
    '/api/redirects': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/redirects/index.get').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/redirects/index.put').default>>>>
    }
    '/api/_hub/**:feature': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxthub+core@0.7.3_ioredis@5.4.1_magicast@0.3.4_rollup@4.18.0_vite@5.3.5_@types+node@20.14.9_terser@5.31.1_/node_modules/@nuxthub/core/dist/runtime/base/server/api/_hub/[...feature]').default>>>>
    }
    '/api/_hub': {
      'head': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxthub+core@0.7.3_ioredis@5.4.1_magicast@0.3.4_rollup@4.18.0_vite@5.3.5_@types+node@20.14.9_terser@5.31.1_/node_modules/@nuxthub/core/dist/runtime/base/server/api/_hub/index.head').default>>>>
    }
    '/api/_hub/manifest': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxthub+core@0.7.3_ioredis@5.4.1_magicast@0.3.4_rollup@4.18.0_vite@5.3.5_@types+node@20.14.9_terser@5.31.1_/node_modules/@nuxthub/core/dist/runtime/base/server/api/_hub/manifest.get').default>>>>
    }
    '/api/_hub/openapi': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxthub+core@0.7.3_ioredis@5.4.1_magicast@0.3.4_rollup@4.18.0_vite@5.3.5_@types+node@20.14.9_terser@5.31.1_/node_modules/@nuxthub/core/dist/runtime/openapi/server/api/_hub/openapi.get').default>>>>
    }
    '/api/_hub/blob/**:pathname': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxthub+core@0.7.3_ioredis@5.4.1_magicast@0.3.4_rollup@4.18.0_vite@5.3.5_@types+node@20.14.9_terser@5.31.1_/node_modules/@nuxthub/core/dist/runtime/blob/server/api/_hub/blob/[...pathname].delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxthub+core@0.7.3_ioredis@5.4.1_magicast@0.3.4_rollup@4.18.0_vite@5.3.5_@types+node@20.14.9_terser@5.31.1_/node_modules/@nuxthub/core/dist/runtime/blob/server/api/_hub/blob/[...pathname].get').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxthub+core@0.7.3_ioredis@5.4.1_magicast@0.3.4_rollup@4.18.0_vite@5.3.5_@types+node@20.14.9_terser@5.31.1_/node_modules/@nuxthub/core/dist/runtime/blob/server/api/_hub/blob/[...pathname].put').default>>>>
    }
    '/api/_hub/blob/delete-folder': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxthub+core@0.7.3_ioredis@5.4.1_magicast@0.3.4_rollup@4.18.0_vite@5.3.5_@types+node@20.14.9_terser@5.31.1_/node_modules/@nuxthub/core/dist/runtime/blob/server/api/_hub/blob/delete-folder.post').default>>>>
    }
    '/api/_hub/blob/delete': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxthub+core@0.7.3_ioredis@5.4.1_magicast@0.3.4_rollup@4.18.0_vite@5.3.5_@types+node@20.14.9_terser@5.31.1_/node_modules/@nuxthub/core/dist/runtime/blob/server/api/_hub/blob/delete.post').default>>>>
    }
    '/api/_hub/blob/head/**:pathname': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxthub+core@0.7.3_ioredis@5.4.1_magicast@0.3.4_rollup@4.18.0_vite@5.3.5_@types+node@20.14.9_terser@5.31.1_/node_modules/@nuxthub/core/dist/runtime/blob/server/api/_hub/blob/head/[...pathname].get').default>>>>
    }
    '/api/_hub/blob': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxthub+core@0.7.3_ioredis@5.4.1_magicast@0.3.4_rollup@4.18.0_vite@5.3.5_@types+node@20.14.9_terser@5.31.1_/node_modules/@nuxthub/core/dist/runtime/blob/server/api/_hub/blob/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxthub+core@0.7.3_ioredis@5.4.1_magicast@0.3.4_rollup@4.18.0_vite@5.3.5_@types+node@20.14.9_terser@5.31.1_/node_modules/@nuxthub/core/dist/runtime/blob/server/api/_hub/blob/index.post').default>>>>
    }
    '/api/_hub/blob/multipart/:action/**:pathname': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxthub+core@0.7.3_ioredis@5.4.1_magicast@0.3.4_rollup@4.18.0_vite@5.3.5_@types+node@20.14.9_terser@5.31.1_/node_modules/@nuxthub/core/dist/runtime/blob/server/api/_hub/blob/multipart/[action]/[...pathname]').default>>>>
    }
    '/api/_hub/cache/**:key': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxthub+core@0.7.3_ioredis@5.4.1_magicast@0.3.4_rollup@4.18.0_vite@5.3.5_@types+node@20.14.9_terser@5.31.1_/node_modules/@nuxthub/core/dist/runtime/cache/server/api/_hub/cache/[...key].delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxthub+core@0.7.3_ioredis@5.4.1_magicast@0.3.4_rollup@4.18.0_vite@5.3.5_@types+node@20.14.9_terser@5.31.1_/node_modules/@nuxthub/core/dist/runtime/cache/server/api/_hub/cache/[...key].get').default>>>>
      'options': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxthub+core@0.7.3_ioredis@5.4.1_magicast@0.3.4_rollup@4.18.0_vite@5.3.5_@types+node@20.14.9_terser@5.31.1_/node_modules/@nuxthub/core/dist/runtime/cache/server/api/_hub/cache/[...key].options').default>>>>
    }
    '/api/_hub/cache/batch-delete': {
      'options': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxthub+core@0.7.3_ioredis@5.4.1_magicast@0.3.4_rollup@4.18.0_vite@5.3.5_@types+node@20.14.9_terser@5.31.1_/node_modules/@nuxthub/core/dist/runtime/cache/server/api/_hub/cache/batch-delete.options').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxthub+core@0.7.3_ioredis@5.4.1_magicast@0.3.4_rollup@4.18.0_vite@5.3.5_@types+node@20.14.9_terser@5.31.1_/node_modules/@nuxthub/core/dist/runtime/cache/server/api/_hub/cache/batch-delete.post').default>>>>
    }
    '/api/_hub/cache/clear/**:base': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxthub+core@0.7.3_ioredis@5.4.1_magicast@0.3.4_rollup@4.18.0_vite@5.3.5_@types+node@20.14.9_terser@5.31.1_/node_modules/@nuxthub/core/dist/runtime/cache/server/api/_hub/cache/clear/[...base].delete').default>>>>
      'options': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxthub+core@0.7.3_ioredis@5.4.1_magicast@0.3.4_rollup@4.18.0_vite@5.3.5_@types+node@20.14.9_terser@5.31.1_/node_modules/@nuxthub/core/dist/runtime/cache/server/api/_hub/cache/clear/[...base].options').default>>>>
    }
    '/api/_hub/cache': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxthub+core@0.7.3_ioredis@5.4.1_magicast@0.3.4_rollup@4.18.0_vite@5.3.5_@types+node@20.14.9_terser@5.31.1_/node_modules/@nuxthub/core/dist/runtime/cache/server/api/_hub/cache/index.get').default>>>>
    }
    '/api/_hub/database/:command': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxthub+core@0.7.3_ioredis@5.4.1_magicast@0.3.4_rollup@4.18.0_vite@5.3.5_@types+node@20.14.9_terser@5.31.1_/node_modules/@nuxthub/core/dist/runtime/database/server/api/_hub/database/[command].post').default>>>>
    }
    '/api/_hub/database/query': {
      'options': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxthub+core@0.7.3_ioredis@5.4.1_magicast@0.3.4_rollup@4.18.0_vite@5.3.5_@types+node@20.14.9_terser@5.31.1_/node_modules/@nuxthub/core/dist/runtime/database/server/api/_hub/database/query.options').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxthub+core@0.7.3_ioredis@5.4.1_magicast@0.3.4_rollup@4.18.0_vite@5.3.5_@types+node@20.14.9_terser@5.31.1_/node_modules/@nuxthub/core/dist/runtime/database/server/api/_hub/database/query.post').default>>>>
    }
    '/api/_hub/kv/**:path': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxthub+core@0.7.3_ioredis@5.4.1_magicast@0.3.4_rollup@4.18.0_vite@5.3.5_@types+node@20.14.9_terser@5.31.1_/node_modules/@nuxthub/core/dist/runtime/kv/server/api/_hub/kv/[...path]').default>>>>
    }
    '/images/:pathname': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/images/[pathname].get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/nuxt@3.12.4_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_@types+node@20.14.9_encoding@0.1.1_cu6mymf3lhirgq43i47sptbq2u/node_modules/nuxt/dist/core/runtime/nitro/renderer').default>>>>
    }
  }
}
export {}