// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 8/30/2024, 4:31:09 PM
const configMerger = require("/Users/robertbeaney/Web Sites/dance-cloud/node_modules/.pnpm/@nuxtjs+tailwindcss@6.12.1_magicast@0.3.4_rollup@4.18.0/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["/Users/robertbeaney/Web Sites/dance-cloud/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/robertbeaney/Web Sites/dance-cloud/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/robertbeaney/Web Sites/dance-cloud/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/robertbeaney/Web Sites/dance-cloud/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/robertbeaney/Web Sites/dance-cloud/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/robertbeaney/Web Sites/dance-cloud/app/plugins/**/*.{js,ts,mjs}","/Users/robertbeaney/Web Sites/dance-cloud/app/composables/**/*.{js,ts,mjs}","/Users/robertbeaney/Web Sites/dance-cloud/app/utils/**/*.{js,ts,mjs}","/Users/robertbeaney/Web Sites/dance-cloud/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/robertbeaney/Web Sites/dance-cloud/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/robertbeaney/Web Sites/dance-cloud/app/app.config.{js,ts,mjs}"] }));

module.exports = (() => {const cfg=config;cfg["content"]["11"] = "/Users/robertbeaney/Web Sites/dance-cloud/.nuxt/content-cache/parsed/**/*.{md,yml,yaml,json}";;return cfg;})()
